keywords: 

favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

rss: atom.xml

toc: false

mathjax: true

copyright: 
  enable: false
  author:  
  license: 

header:
  author: lanthora

gitalk:
  enable: true
  on: false
  owner: lanthora
  repo: lanthora.github.io
  admin: ['lanthora']
  clientID: 326a600f11c887f1fb1d
  clientSecret: 2fc1a0f0494481c9ad81272a041e854d49470d09

nav_name: LANTHORA

nav: 
  -
    name: GitHub
    path: "https://github.com/lanthora"
    blank: true
  -
    name: Gmail
    path: "mailto:nierunjie@gmail.com"
    blank: true
