keywords: 

favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

rss: atom.xml

toc: false

mathjax: true

copyright: 
  enable: false
  author:  
  license: 

header:
  author: lanthora

nav_name: LANTHORA

nav: 
  -
    name: GitHub
    path: "https://github.com/lanthora"
    blank: true
  -
    name: Gmail
    path: "mailto:nierunjie@gmail.com"
    blank: true
